---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-celery
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}-celery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}-celery
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-celery
      {{- if eq .Values.env "staging" }}
      annotations:
        iam.amazonaws.com/role: {{ .Values.assume_role }}
      {{- end }}
    spec:
      containers:
        - name: {{ .Values.name }}-celery
          image: {{ .Values.docker_registry | default "mozillaparsys" }}/{{ .Values.name }}:{{ .Values.rev }}
          {{ if eq .Values.env "dev" -}}
          imagePullPolicy: IfNotPresent
          {{- else -}}
          imagePullPolicy: Always
          {{- end }}
          command: ["/bin/sh"]
          {{ if eq .Values.env "staging" -}}
          args: ["-c", "/code/bin/run-k8s.sh celery"]
          volumeMounts:
          - name: secret-volume
            readOnly: true
            mountPath: "/etc/secrets-volume"
          {{- else -}}
          args: ["-c", "/code/bin/run-celery.sh"]
          {{- end }}
          env:
            - name: C_FORCE_ROOT
              value: 'true'
          envFrom:
            - configMapRef:
                name: {{ .Values.config_map }}
      {{- if eq .Values.env "staging" }}
      volumes:
      - name: secret-volume
        secret:
          secretName: mozillians-env
      {{- end }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-celery-beat
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}-celery-beat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}-celery-beat
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-celery-beat
      {{- if eq .Values.env "staging" }}
      annotations:
        iam.amazonaws.com/role: {{ .Values.assume_role }}
      {{- end }}
    spec:
      containers:
        - name: {{ .Values.name }}-celery-beat
          image: {{ .Values.docker_registry | default "mozillaparsys" }}/{{ .Values.name }}:{{ .Values.rev }}
          {{ if eq .Values.env "dev" -}}
          imagePullPolicy: IfNotPresent
          {{- else -}}
          imagePullPolicy: Always
          {{- end }}
          command: ["/bin/sh"]
          {{ if eq .Values.env "staging" -}}
          args: ["-c", "/code/bin/run-k8s.sh celery-beat"]
          volumeMounts:
          - name: secret-volume
            readOnly: true
            mountPath: "/etc/secrets-volume"
          {{- else -}}
          args: ["-c", "/code/bin/run-celery-beat.sh"]
          {{- end }}
          env:
            - name: C_FORCE_ROOT
              value: 'true'
          envFrom:
            - configMapRef:
                name: {{ .Values.config_map }}
      {{- if eq .Values.env "staging" }}
      volumes:
      - name: secret-volume
        secret:
          secretName: mozillians-env
      {{- end }}

