{{ if eq .Values.env "dev" -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-mysql
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}-mysql
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-mysql
    spec:
      containers:
        - name: {{ .Values.name }}-mysql
          image: mariadb:10.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: mozillians
            - name: MYSQL_USER
              value: mozillians
            - name: MYSQL_PASSWORD
              value: mozillians
            - name: MYSQL_ROOT_PASSWORD
              value: root

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-redis
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}-redis
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-redis
    spec:
      containers:
        - name: {{ .Values.name }}-redis
          image: redis:3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-memcached
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}-memcached
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}-memcached
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-memcached
    spec:
      containers:
        - name: {{ .Values.name }}-memcached
          image: memcached
          imagePullPolicy: IfNotPresent

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-es
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}-es
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}-es
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-es
    spec:
      containers:
        - name: {{ .Values.name }}-es
          image: elasticsearch:2.4.5
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-mysql-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.name }}-mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-redis-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.name }}-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-memcached-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.name }}-memcached
  ports:
    - protocol: TCP
      port: 11211
      targetPort: 11211

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-es-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.name }}-es
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
{{- end -}}
