---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
      {{- if eq .Values.env "staging" }}
      annotations:
        iam.amazonaws.com/role: {{ .Values.assume_role }}
      {{- end }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.docker_registry | default "mozillaparsys" }}/{{ .Values.name }}:{{ .Values.rev }}
          {{ if eq .Values.env "dev" -}}
          imagePullPolicy: IfNotPresent
          {{- else -}}
          imagePullPolicy: Always
          {{- end }}
          ports:
            - containerPort: 8000
          command: ['/bin/sh']
          {{ if eq .Values.env "staging" -}}
          args: ["-c", "/code/bin/run-k8s.sh run-prod"]
          volumeMounts:
          - name: secret-volume
            readOnly: true
            mountPath: "/etc/secrets-volume"
          {{- else -}}
          args: ["-c", "/code/bin/run-dev-preview.sh"]
          {{- end -}}
          {{ if eq .Values.env "dev" }}
          tty: true
          stdin: true
          envFrom:
            - configMapRef:
                name: {{ .Values.config_map }}
          env:
            - name: DUMMY_TIMESTAMP
              value: "{{ now.Unix }}"
          {{- end }}
      {{- if eq .Values.env "staging" }}
      volumes:
      - name: secret-volume
        secret:
          secretName: mozillians-env
      {{- end }}
